Language updates - promises!
CruGlobal/godtools-ios pull request #50
Opened 2016-12-09 14:27 UTC by ryancarlson

This PR includes updates to improve the language/translation updating process:
- Move from notification based to promise based interactions
- Removes code for publish, create, delete drafts to simplify code base _(pending Ann's approval)_
- Make download button in languages page cells functional - it wasn't wired to anything
- Auto download selected (primary) language on app launch if there are new items published in that language
  - Feedback from Ann was that people were unaware of the need to go update, and that notifications on app launch were not a good solution
- Move away from major/minor version update distinction, temporarily? The API doesn't support this distinction in the way we intended. 
   - The consequence is that full packages are downloaded when updated.
   - The benefit is a simpler code base
   - The rationale is that we don't update enough things that often that this becomes a major concern.
   - This can be added back in in a promise based approach if it's necessary.

2016-12-09 14:29 UTC, ryancarlson commented
@michaelharro submitting this to Apple for review now. Would you be able to review?

@LizzyRandall I'd like to you take a look too to see how this code is working and familiarize yourself with some of the patterns we're trying to move to. We can talk if you have questions.

(I will definitely want to squash before merging on this one)

2016-12-09 15:00 UTC, LizzyRandall requested changes
See my two comments, otherwise 👍  I've seen PKPromises with Voke, that's a great idea to use them besides API calls

2016-12-09 15:00 UTC, LizzyRandall commented on godtools/godtools-ios-api/GTDataImporter.m
> +                                             RXMLElement *contents = [weakSelf.packageExtractor unzipResourcesAtTarget:targetPath forLanguage:language package:nil];
I would think this could be reworked to not be so many nested if statements.
Like if(response.statusCode != 200) then error stuff, return (if possible) and then the next statements below the could assume the status code is 200
Or potentially a switch since the status code is a number right?

2016-12-09 15:00 UTC, LizzyRandall commented on godtools/Controllers/GTLanguagesViewController.m
> +    if ([chosen.downloaded boolValue] && !chosen.hasUpdates) {
Wouldn't the standards usually have something like chosen.downloaded.boolValue instead of [chosen.downloaded boolValue]? Or is that too many dots in one line?

2016-12-12 15:42 UTC, ryancarlson commented on godtools/Controllers/GTLanguagesViewController.m
> +    if ([chosen.downloaded boolValue] && !chosen.hasUpdates) {
Sure, updated.

2016-12-12 15:45 UTC, ryancarlson commented on godtools/godtools-ios-api/GTDataImporter.m
> +                                             RXMLElement *contents = [weakSelf.packageExtractor unzipResourcesAtTarget:targetPath forLanguage:language package:nil];
I agree this section is rough, but I've intentionally avoided touching the code that translates the API response into XML and parses it. There's plenty of rework that could be done here, but I think doing this would only be scratching the surface and could introduce bugs.

My work in this PR is to move away from notification/observer based interactions with the API & data importer to promises & resolvers. Anything beyond that is another can of worms that I'd rather not open right now.

2016-12-12 15:56 UTC, LizzyRandall approved these changes

2016-12-13 14:11 UTC, merged

2016-12-15 23:46 UTC, michaelharro commented
@ryancarlson this is an impressive PR. It has dramatically increased the readability and quality of the code base. Well done.

Also good review @LizzyRandall I don't have any more to say. The only thing I was concerned about was the fact there wasn't a one for one replacement of functionality but I went back a read your PR description and it looks like that was deliberate. If Ann is happy with the functionality the code looks great.

2016-12-19 14:59 UTC, ryancarlson commented
thanks for the feedback @michaelharro !